### ISSUE TITLE
Sample Dependency?

### ISSUE THREAD

**Issue by phillip-haydon** [mrklintscher/YoutubeSearch#1]
Hey,

The nuget package seems to depend on SampleDependency:

https://www.nuget.org/packages/SampleDependency/

https://www.nuget.org/packages/YoutubeSearch.dll/

I don't think this is intended?

**Comment by mrklintscher** [comment]
Hi,

yes you are right. I have to fix it.

**Comment by mrklintscher** [comment]
FIXED
