### ISSUE TITLE
Title of result is error unicode font

### ISSUE THREAD

**Issue by thanhhaiek** [mrklintscher/YoutubeSearch#18]
Title of result is error unicode font. How to resolve. Thanks

**Comment by mark222in** [comment]
this because webclient
in VideoSearch.cs use: 
     using (WebClient wc = new WebClient { Encoding = Encoding.UTF8 })
                {
                    string html = wc.DownloadString(YtQueryUrl + querystring + "&page=" + i);
                }

**Comment by mrklintscher** [comment]
Closed no example code received.
