### ISSUE TITLE
There is no version 1.2.0?

### ISSUE THREAD

**Issue by renanrcp** [mrklintscher/YoutubeSearch#19]
Hello guys, I was needing the SearchQueryAsync method, because my application is totally asynchronous, I noticed that it was to have a version 1.2.0 but I could not find it, if anyone knows why, please let me know.

**Comment by Mayerch1** [comment]
It is not available as a NuGet Package yet (@mrklintscher).
But for now you can clone this repository and compile the project.

**Comment by renanrcp** [comment]
Yes, I did that at the time thanks xD

**Comment by mrklintscher** [comment]
https://www.nuget.org/packages/YouTubeSearch/

Please use the new build and package.
