### ISSUE TITLE
NuGet update

### ISSUE THREAD

**Issue by takoz53** [mrklintscher/YoutubeSearch#20]
Please update the NuGet for the usage of the Async Method of SearchQuery.

**Comment by Mayerch1** [comment]
To finally address this issue:
I think the NuGet should be updated too, However only @mrklintscher can update the package.
I've seen multiple forks offering async calls, which are already implemented in 1.2.0 of this repo. And I think the quality of the async support of this repo is higher than the forks.

(Another request mentioned in #19)

**Comment by mrklintscher** [comment]
https://www.nuget.org/packages/YouTubeSearch/

Finally updated!
