### ISSUE TITLE
Unescaped html results

### ISSUE THREAD

**Issue by nitanmarcel** [mrklintscher/YouTubeSearch#29]
The results seems to be un-escaped and this seems to cause some small problems.

For example the character " ' " comes as `#39,t`:

![image](https://user-images.githubusercontent.com/41646249/79382852-d978f580-7f6c-11ea-8889-3653a6c58c37.png)

**Comment by nitanmarcel** [comment]
I've opened a PR that fixes this, have a look https://github.com/mrklintscher/YouTubeSearch/pull/30

**Comment by mrklintscher** [comment]
https://github.com/mrklintscher/YouTubeSearch/commit/05927388c4560aabf1af0597f5078027b68b7ea8

**Comment by nitanmarcel** [comment]
Way better than my PR. Also shouldn't be the url encoded or the WebClient does that automatically?

**Comment by nitanmarcel** [comment]
@mrklintscher  Also another bugI found is the video description which it keeps the html blocks and inline elements as seen here:

![image](https://user-images.githubusercontent.com/41646249/79436289-5cd03080-7fd9-11ea-9486-e81ba5b4176a.png)
