### ISSUE TITLE
Calls not returning with Youtube Hits

### ISSUE THREAD

**Issue by PhillipSargeant** [mrklintscher/YouTubeSearch#34]
GREAT program!

However, occasionally the await calls to videos.GetVideos(querystring, querypages) and playlist.GetPlaylists(querystring, querypages) complete without finding any hits, even though valid hits are there on Youtube.

If the call is repeated (sometimes more than a couple of times) it does return with the list of hits. 

Even though the call occasionally completes without finding any hits it appears that the calls really need extra time to find these valid hits before returning from the await call with zero hits.

Cheers
Phil Sargeant

**Comment by narqs** [comment]
Hey! i'm having the same problem, it seems like youtube have updated their way of showing html? 
When using HttpClient.GetAsync() it sometime returns html containing (yt-lockup-content) but mostly it doesn't... and that results in no valid hits.

**Comment by mrklintscher** [comment]
Yes they changed their page structure.

I will fix this asap.

**Comment by PhillipSargeant** [comment]
Hello Torsten,

 

Thank you for your effort.

 

You may notice that every now and again the content returned from string content = await Web.getContentFromUrl("https://www.youtube.com/results?search_query=" + querystring + "&page=" + i);

within GetVideos is different. This is not occurring often but it does occur.

 

I’m puzzled as to why exactly the same call to YouTube produces two different results.

 

Mostly one receives the following:

 

<!doctype html><html  style=\"font-size: 10px;font-family: Roboto, Arial, sans-serif;\" lang=\"en-GB\" dir=\"ltr\" gl=\"AU\"><head><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" /><meta http-equiv=\"origin-trial\" data-feature=\"Web Components V0\" data-expires=\"2020-10-23\" content=\"AhbmRDASY7NuOZD9cFMgQihZ+mQpCwa8WTGdTx82vSar9ddBQbziBfZXZg+ScofvEZDdHQNCEwz4yM7HjBS9RgkAAABneyJvcmlnaW4iOiJodHRwczovL3lvdXR1YmUuY29tOjQ0MyIsImZlYXR1cmUiOiJXZWJDb21wb25lbnRzVjAiLCJleHBpcnkiOjE2MDM0ODY4NTYsImlzU3ViZG9tYWluIjp0cnVlfQ==\"><meta http-equiv=\"origin-trial\" data-feature=\"Web Components V0\" data-expires=\"2020-10-27\" content=\"Av2+1qfUp3MwEfAFcCccykS1qFmvLiCrMZ//pHQKnRZWG9dldVo8HYuJmGj2wZ7nDg+xE4RQMQ+Ku1zKM3PvYAIAAABmeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZS5jb206NDQzIiwiZmVhdHVyZSI6IldlYkNvbXBvbmVudHNWMCIsImV4cGlyeSI6MTYwMzgzNjc3MiwiaXNTdWJkb21haW4iOnRydWV9\"><meta http-equiv=\"origin-trial\" ………………………………………………………………………………………..

 

 

But every now and again one receives:

 

<!DOCTYPE html><html lang=\"en-GB\" data-cast-api-enabled=\"true\"><head><style name=\"www-roboto\" >@font-face{font-family:'Roboto';font-style:normal;font-weight:400;src:local('Roboto Regular'),local('Roboto-Regular'),url(//fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxP.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:italic;font-weight:400;src:local('Roboto Italic'),local('Roboto-Italic'),url(//fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1Mu51xIIzc.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:italic;font-weight:500;src:local('Roboto Medium Italic'),local('Roboto- ………………………………………………………………

 

Obviously when this occurs the Regex Match fails and no items result.

 

I overcome this in my program with some retries but I thought I would bring it to your attention.

 

Cheers

Phil
