### ISSUE TITLE
getTitle() cannot get non-english title

### ISSUE THREAD

**Issue by tuhin24** [mrklintscher/YouTubeSearch#35]
Good work. For non-English metadata, it returns gibberish. Can it be fixed?

Thanks

**Comment by mrklintscher** [comment]
Can you please share data and output.

**Comment by tuhin24** [comment]
Please search for title "bangla natak" as below:

`string querystring = "bangla natak";
int querypages = 1;

VideoSearch videos = new VideoSearch();
var items = await videos.GetVideos(querystring, querypages);

foreach (var item in items)
{
    Console.WriteLine("Title: " + item.getTitle());
    
}`

Output:

à¦…à¦¤à§à¦¯à¦¾à¦šà¦¾à¦°à§€ à¦¬à¦‰ | Ottachari Bou | New Natok | Tisha | Chanchal Chowdhury | Bangla New Natok 2020
Epitaph | Mehzabien, Tawsif Mahbub, Irfan Sazzad, Shamim Hasan | Bangla Natok 2020 | Maasranga TV
Biye | à¦¬à¦¿à¦¯à¦¼à§‡ | Eid Natok 2020 | Apurba | Mehazabien | Bangla New Natok | Bangladeshi Drama
Couple goals | à¦•à¦¾à¦ªà¦² à¦—à§‹à¦²à¦¸ | Musfiq R Farhan, Payel, Anik, Siam | Mahmud Mahin | New Bangla Natok
Thanda Gorom | Zahid Hasan | Mehazabien | Shamim Hasan Sarkar | Arfan Ahmed | Bangla Natok
Diaryer Pata Theke | Apurba | Tanjin Tisha | Nazmul Roni | Bangla New Natok 2020
Comedy Natok: Ultimetum | à¦†à¦²à¦Ÿà¦¿à¦®à§‡à¦Ÿà¦¾à¦® | Afran Nisho, Tisha, Dr. Ejajul, Fazlur Rahman Babu
Tui Morisne Kya | Bangla New Natok 2020 | Chanchal Chowdhury | Fazlur Rahman Babu | New Natok 2020
Bangla New Eid Natok 2020 || Purnima || Apurbo
Valobasha Mitthe Noy | Eid Natok 2020 | Irfan Sajjad | Mehazabien Chowdhury | Bangla New Natok
DOUBLE TROUBLE || Parsa Evana || Shawon || Payel || Bangla New Natok 2020 || @G Series Bangla Natok
Hanif Sanket Eid ul-fitr Natok - Thik Thikana - à¦ à¦¿à¦• à¦ à¦¿à¦•à¦¾à¦¨à¦¾ 2010
Love Box (à¦²à¦¾à¦­ à¦¬à¦•à§à¦¸) Tahsan, Sabila Noor | Eid Natok
Bra Ther | à¦¬à§à¦°à¦¾-à¦¦à¦¾à¦°  | Afran Nisho | Mehazabien Chowdhury | New Bangla Natok
Viral Masud | à¦­à¦¾à¦‡à¦°à¦¾à¦² à¦®à¦¾à¦¸à§à¦¦ | Mosharraf Karim | Sifat Tahsin | Eid Natok2020 | New Comedy Natok 2020
Tumi Nai | à¦¤à§à¦®à¦¿ à¦¨à¦¾à¦‡ | Eid Natok 2020 | Apurba | Momo | Bangla New Natok | New Natok 2020
Ucchotoro Bhalobasha (à¦‰à¦šà§à¦šà¦¤à¦° à¦­à¦¾à¦²à§‹à¦¬à¦¾à¦¸à¦¾) | Ft. Mosharraf Karim, Zakia Bari Momo | Rtv Eid Natok 2020
MODERN GIRL | à¦®à¦¡à¦¾à¦°à§à¦¨ à¦—à¦¾à¦°à§à¦² | Bangla New Natok 2020 | Shajal | Nusrat Roohi | Anik | Channel F3
Hotath Dekha | à¦¹à¦ à¦¾à§Ž à¦¦à§‡à¦–à¦¾ | Apurba | Tanjin Tisha | Kajal Arefin Ome | Eid Drama
Bondhu Express | Alen Shuvro | Shawon | Tasnuva Elvin | Asif Bin Azad | Bangla New Natok
à¦¬à¦¿à¦¯à¦¼à§‡à¦° Side Effects | Musfiq R Farhan | Payel | Mukit Zakaria | Mim | Anik | Mahmud Mahin
Kabir Khan Er Boomerang | à¦•à¦¬à§€à¦° à¦–à¦¾à¦¨ à¦à¦° à¦¬à§à¦®à§‡à¦°à¦¾à¦‚ | Tawsif Mahbub | Ahona | Topu Khan | New Eid Natok
Ashikkhito | à¦…à¦¶à¦¿à¦•à§à¦·à¦¿à¦¤ || Salauddin Lavlu || Zakia Bari Mamo | Eid Natok 2020 | Bangla New Natok 2020
à¦…à¦¤à§à¦¯à¦¾à¦šà¦¾à¦°à§€ à¦¨à§‡à¦¤à¦¾ | Attochari Neta | New Natok | Mahfuz Ahmed | Tisha | Bangla New Natok 2020
Devdas Juliet | à¦¦à§‡à¦¬à¦¦à¦¾à¦¸ à¦œà§à¦²à¦¿à¦¯à¦¼à§‡à¦Ÿ | Eid Natok 2020 | Afran Nisho | Tasnia Farin | Bangla New Natok
Char Copy 100 (à¦šà¦¾à¦° à¦•à¦ªà¦¿ à§§à§¦à§¦) | Ft. Jovan, Sarika Sabrin | New Romantic Natok 2020 | Rtv Drama
Sei Cokh | à¦¸à§‡à¦‡ à¦šà§‹à¦– | Jahid Hasan, Mou, Azad Abul Kalam | Bangla Natok
Photo Frame | à¦«à¦Ÿà§‹ à¦«à§à¦°à§‡à¦® | Eid Natok 2020 | Afran Nisho | Mehazabien Chowdhury | Bangla New Natok
Tumi Ami Ar Disturb || Mosharraf Karim || Payel | Bangla New Eid Natok 2020 |@G Series Bangla Natok
The thread 0x1ef0 has exited with code 0 (0x0).

**Comment by mrklintscher** [comment]
Try it in an forms app please then it should go.
