### ISSUE TITLE
Video downloading stopped working

### ISSUE THREAD

**Issue by Lyrapuff** [mrklintscher/YouTubeSearch#37]
Hello, I've implemented audio downloading in my unity project (android), it worked well until approximately yesterday, I wonder if YouTube has changed anything, so it's not working now?

**Comment by mrklintscher** [comment]
Yes they changed deciphering.

We need to fix!

Look here. 

https://github.com/Tyrrrz/YoutubeExplode/issues/427

**Comment by mrklintscher** [comment]
Fixed
