### ISSUE TITLE
cant download video URL https://youtube.com/watch?v=A0Sc2CLqEmk 

### ISSUE THREAD

**Issue by gpswat72** [mrklintscher/YouTubeSearch#38]
YouTubeSearch.ParseException: Could not parse the Youtube page for URL https://youtube.com/watch?v=A0Sc2CLqEmk 
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues ---> System.NullReferenceException

**Comment by mrklintscher** [comment]
Which JSON version do you use?
Do you use the latest code?
Which OS do you use?

Best regards,
mrklintscher

**Comment by gpswat72** [comment]
Youtubesearch 2.2.3 
NewtonSoft.Json 12.0.3 
Os windows 7 x64 
Netframework 4.6.1

**Comment by mrklintscher** [comment]
You need to use Newton 10.0.x

-------- Ursprüngliche Nachricht --------Von: gpswat72 <notifications@github.com> Datum: 07.08.20  17:48  (GMT+01:00) An: mrklintscher/YouTubeSearch <YouTubeSearch@noreply.github.com> Cc: Torsten Klinger <torsten.klinger@googlemail.com>, Comment <comment@noreply.github.com> Betreff: Re: [mrklintscher/YouTubeSearch] cant download video URL https://youtube.com/watch?v=A0Sc2CLqEmk  (#38) 
Youtubesearch 2.2.3
NewtonSoft.Json 12.0.3
Os windows 7 x64
Netframework 4.6.1

**Comment by gpswat72** [comment]
ok thanks
