### ISSUE TITLE
not work with Unity (android)

### ISSUE THREAD

**Issue by Ali1Jamal** [mrklintscher/YouTubeSearch#39]
Hello.
i test your project and Work very well with unity on pc platform but when  i am try to run it on android by using unity game engine it dose not work .
I added media access and internet access, but it didn't work.
here is my project i am using unity 2018.3
https://mega.nz/file/XAVW0I6T#EUC0GYcniXhohelAaUlt1ufA9u9FCtQ6A1c_dpK_2Hg

**Comment by mrklintscher** [comment]
Which error code is returnd?

**Comment by Ali1Jamal** [comment]
Thank you for the fast reply.
i fix the problem by doing this :
i export unity error logs on my android device its says "platformnotsupportedexception: operation is not supported unity".
so i search about this error and i found this:
https://github.com/JamesNK/Newtonsoft.Json/issues/2046
i fix the problem by doing this "Changing "API Compatibility Level" in Unity configuration to .NET 4.x ".
And now I was able to download the video to my Android phone.
I wish you a good time.
