### ISSUE TITLE
Can't get videos from playlist

### ISSUE THREAD

**Issue by pictos** [mrklintscher/YouTubeSearch#40]
when you call the `GetPlaylistItems(string Playlisturl)` method it returns zero items.

**Comment by mrklintscher** [comment]
Yes you are right.
They changed something on the page structure.
-------- Ursprüngliche Nachricht --------Von: Pedro Jesus <notifications@github.com> Datum: 13.09.20  00:50  (GMT+01:00) An: mrklintscher/YouTubeSearch <YouTubeSearch@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [mrklintscher/YouTubeSearch] Can't get videos from playlist (#40) 
when you call the GetPlaylistItems(string Playlisturl) method it returns zero items.
