### ISSUE TITLE
Could not parse the Youtube page for URL https://youtube.com/watch?v=5gQmDY-05vg

### ISSUE THREAD

**Issue by kapasifulop** [mrklintscher/YouTubeSearch#41]
### My Problem
Hi! When I try to download [this](https://youtube.com/watch?v=5gQmDY-05vg) video, I get this error code:
```
Could not parse the Youtube page for URL https://youtube.com/watch?v=5gQmDY-05vg
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues
```
![image](https://user-images.githubusercontent.com/69323434/97168232-6278b100-1788-11eb-9164-d25b59031544.png)
But when I try to download [this](https://www.youtube.com/watch?v=9rGm3Dal5kc) video, sometimes it works but sometimes I get the same error code.

### My code:
```
IEnumerable<VideoInfo> videos = YouTubeSearch.DownloadUrlResolver.GetDownloadUrls(url); //ERROR CODE IS HERE
video = videos.First(predicate => predicate.VideoType == VideoType.Mp4 && predicate.Resolution == Convert.ToInt32(360));
if(video.RequiresDecryption) DownloadUrlResolver.DecryptDownloadUrl(video);
DownloadFile(video.DownloadUrl, video.Title, System.AppDomain.CurrentDomain.BaseDirectory + "temp\\", video.AudioExtension);
```
|             |   |
|---------|--|
|OS version| Windows 10 Pro (10.0.19041 Build 19041)|
|.Net framework|V4.8|
|YoutubeSearch|V2.2.5|
|Newton.Json|V12.0.3|

**Comment by mrklintscher** [comment]
Hi,

nice to meet you.

On which platform do you use it?

Kapási Fülöp <notifications@github.com> schrieb am Mo., 26. Okt. 2020,
12:40:

**Comment by kapasifulop** [comment]
My project is in WPF c#.

**Comment by mrklintscher** [comment]
Try use json 10.0.3

Kapási Fülöp <notifications@github.com> schrieb am Mo., 26. Okt. 2020,
18:28:

**Comment by kapasifulop** [comment]
When I use Newton.Json 10.0.3 I always get that error code.

**Comment by mrklintscher** [comment]
Please zip your code and send it torsten.klinger@googlemail.com

Kapási Fülöp <notifications@github.com> schrieb am Mo., 26. Okt. 2020,
19:29:

**Comment by kapasifulop** [comment]
The code is on github, in private, for additional help I'd like to invite you to the project.

**Comment by mrklintscher** [comment]
Ok yes

Kapási Fülöp <notifications@github.com> schrieb am Mo., 26. Okt. 2020,
19:34:

**Comment by kapasifulop** [comment]
![image](https://user-images.githubusercontent.com/69323434/97219307-1a7a7e00-17ca-11eb-914c-ad05717e2f56.png)
I sent you an invitation.

**Comment by kapasifulop** [comment]
I updated the youtube search version to 2.2.6 but isn't work.

**Comment by mrklintscher** [comment]
Then you are doing something wrong.

Send me the sources to me@mrklintscher.de

Kapási Fülöp <notifications@github.com> schrieb am Mi., 4. Nov. 2020, 15:41:
