### ISSUE TITLE
Encodings problem

### ISSUE THREAD

**Issue by vasilewvv** [mrklintscher/YoutubeSearch#5]
РњСѓР¶СЃРєРѕРµ Р”РІРёР¶РµРЅРёРµ(РњСѓР¶СЃРєРѕРµ Р“РѕСЃСѓРґР°СЂСЃС‚РІРѕ) РёР»Рё РєР°Рє СЃС‚Р°С‚СЊ РІС‹СЃРѕРєРѕСЂР°РЅРіРѕРІС‹Рј СЃР°РјС†РѕРј | LOONY

from reading Russan videos # #

**Comment by newbiedeveloper9** [comment]
Use custom encoding
webClient.Encoding = Encoding.UTF8;
or smth like this.
