### ISSUE TITLE
Support for async query

### ISSUE THREAD

**Issue by Mayerch1** [mrklintscher/YoutubeSearch#7]
Is it possible to add functionality for asynchronous execution of the search?

I have seen that a pull request was rejected due to incompatibility with mobile devices.

I would suggest to upgrade the solution to .Net 4.5.

The upgrade enables you to change 
`webclient.DownloadString` to the new function `await webclient.DownloadStringTaskAsync`.

If you support this changes I can start a pull request.

Edit:
As .Net 4.5 was released in 2012 the distribution of it should be good enought.
Users of .Net 4.0 could still use an older build.

Edit 2:
I just saw, that this project is already targeting 4.5 or higher, so that souldn't be a problem.
My Visual Studio set it to 4.0 when I cloned the repository.

**Comment by mrklintscher** [comment]
https://github.com/mrklintscher/YoutubeSearch/pull/8?_pjax=%23js-repo-pjax-container
